---
sudo: false
language: ruby
cache: bundler
rvm: 2.6.3
before_install: gem install bundler -v 1.17.3
services: docker
before_install:
  - docker run -d -p 6379:6379 redislabs/redisearch:latest --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
script: bundle exec $COMMAND
matrix:
  include:
    - env: COMMAND='rake test'
    - env: COMMAND=rubocop
