---
env:
  global:
    - CC_TEST_REPORTER_ID=fec34310f03fd2cc767a85fa23d5102f3dca67b9cc967a48d9940027731394e8
sudo: false
language: ruby
cache:
  directories:
   - gemfiles/vendor/bundle
   - /home/travis/.rvm/
services: docker
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - docker run -d -p 6379:6379 redislabs/redisearch:latest --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
rvm:
  - 2.6
  - 2.5
gemfile:
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
jobs:
  include:
    - stage: Lint
      script: bundle exec rubocop --config=./.rubocop.yml
      rvm: 2.6
