name: lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install rubocop
      run: |
        gem install rubocop rubocop-performance rubocop-minitest
    - name: Lint
      run: rubocop --config=./.rubocop.yml --parallel
